### ISSUE TITLE
Compatible USB2EPP adapter

### ISSUE THREAD

**Issue by s-weigand** [acpo/PiSpec20_stellarnet#4]
First of all thanks for for this project. ❤️ 
We want to transition from using a PC with LabView to control our `StellarNet EPP2000` with a RaspberryPi for students to do remote experiments.
Only Problem is that our `USB2EPP` adapter from StellarNet has some hardware problems and StellarNet doesn't sell them anymore.
So I was wandering if you still uses the original `USB2EPP` adapter or if you found a compatible adapter (since you also mention the USB2EPP version).
https://github.com/acpo/PiSpec20_stellarnet/blob/85b0a9d4f6c9f7188d3a06ce55c3f86c4f595c87/PiSpec20_stellarnet/stellarnet.py#L119-L121

Another option for us would be to use [this hat for the RaspberryPi](https://github.com/worlickwerx/pi-parport) and directly talk via `IEEE-1284` but I can't find the spec files for the protocol. 
How did you manage to write the usb driver?
Did you reverse engineer it?
Or do you know where to get the protocol specs?

Thanks a lot in advance.

**Comment by acpo** [comment]
Sebastian,
  The StellarNet hardware that I have is all USB, so I have not had the opportunity to work with the EPP hardware interface.  I think the 'USB2EPP' appears in the files due to legacy issues.
  The driver that comes with this project is from StellarNet.  The driver is on an Apache 2.0 license, so it is free to use and modify.  The StellarNet website still says that they offer Linux drivers for sale, although it seems to have dropped off of their price list after the introduction of the MacOS software (which is essentially a Linux product).  The driver that is included is explicit about working with USB connected devices (notice the `import` statements for `usb.core`  and `usb.util`.
  I would suspect that using the parallel port Hat to connect to the EPP spectrometer would require a lot of work to convert the USB commands to parallel port commands.  Fundamentally, it should be possible to recycle `stellarnet.py` into a driver for the IEEE-1284.  A discussion of converting the driver from USB to EPP is very much beyond my level of understanding.

Best regards

**Comment by s-weigand** [comment]
Sorry for the late reply and thank you for detailed answer.
